-- 6. Write an SQL query to create an index on the email column.

CREATE TABLE EMAIL_INFO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE INDEX EMAIL_INDEX ON EMAIL_INFO(EMAIL);

SELECT * FROM EMAIL_INFO;
SHOW INDEX FROM EMAIL_INFO;
