-- 7. Create a database schema for the student grade system. It contains student data and their grade of each subject based
--    on the different semester.

CREATE DATABASE STUDENT_GRADE_SYSTEM;

USE STUDENT_GRADE_SYSTEM;

CREATE TABLE STUDENT_INFO (
	STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    AGE INT,
    DOB DATE,
    GENDER ENUM('M', 'F', 'O'),
    ADDRESS_CITY VARCHAR(50)
);

CREATE TABLE SUBJECT_INFO (
	SUBJECT_CODE INT PRIMARY KEY AUTO_INCREMENT,
    SUBJECT_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE SEMESTER (
	SEMESTER_ID INT AUTO_INCREMENT PRIMARY KEY,
    SEMESTER INT
);

CREATE TABLE STUDENT_GRADE (
	STUDENT_GRADE_ID INT AUTO_INCREMENT PRIMARY KEY,
	STUDENT_ID INT,
    SUBJECT_CODE INT,
	SEMESTER_ID INT,
    SEMESTER INT,
    GRADE DECIMAL(4,2),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID),
    FOREIGN KEY (SUBJECT_CODE) REFERENCES SUBJECT_INFO(SUBJECT_CODE),
    FOREIGN KEY (SEMESTER_ID) REFERENCES SEMESTER(SEMESTER_ID)
);

SELECT * FROM STUDENT_GRADE;