-- 1. Create a database structure for employee leave application. It should include all the employee's 
--    information as well as their leave information.

CREATE DATABASE EMPLOYEE_LEAVE_APPLICATION;

USE EMPLOYEE_LEAVE_APPLICATION;

CREATE TABLE EMPLOYEE (
	EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    AGE INT NOT NULL,
    SALARY INT NOT NULL,
    POSITION VARCHAR(100),
    DEPARTMENT VARCHAR(150),
    PHONE_NUMBER VARCHAR(255),
    HIRE_DATE DATE,
    ADDRESS VARCHAR(255)
);

CREATE TABLE LEAVE_APPLICATION (
	APPLICATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_ID INT,
    FROM_DATE DATE NOT NULL,
    TO_DATE DATE NOT NULL,
    REASON TEXT,
    STATUS ENUM('APPROVED', 'PENDING', 'REJECTED') DEFAULT  'PENDING',
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);