# 8. Write a SQL query to retrieve the names of all customers who have made orders in the "orders" table and have ordered products in all categories.

SELECT * FROM CUSTOMERS;
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;

SELECT C.CUSTOMER_NAME, COUNT(O.CUSTOMER_ID) AS TOTAL_ORDERS, GROUP_CONCAT(DISTINCT CT.CATEGORY_NAME SEPARATOR ', ') AS CATEGORY_NAME FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
JOIN CATEGORIES CT ON P.CATEGORY_ID = CT.CATEGORY_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING COUNT(DISTINCT CT.CATEGORY_ID) = (SELECT COUNT(*) FROM CATEGORIES);