-- 2. Write a SQL query to retrieve the names and total revenue generated by all customers in the "orders" table, sorted by revenue in descending order.

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(100),
    CUSTOMER_EMAIL VARCHAR(100),
    COUNTRY VARCHAR(100)
);

CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10, 2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

INSERT INTO CUSTOMERS (CUSTOMER_ID, CUSTOMER_NAME, CUSTOMER_EMAIL, COUNTRY) VALUES
(1, 'John Doe', 'john@example.com', 'USA'),
(2, 'Jane Smith', 'jane@example.com', 'India'),
(3, 'Alice Johnson', 'alice@example.com', 'USA'),
(4, 'Michael Brown', 'michael@example.com', 'Canada'),
(5, 'Emily Davis', 'emily@example.com', 'China'),
(6, 'Daniel Wilson', 'daniel@example.com', 'Japan'),
(7, 'Sarah Martinez', 'sarah@example.com', 'Russia'),
(8, 'James Anderson', 'james@example.com', 'Canada'),
(9, 'Olivia Taylor', 'olivia@example.com', 'USA'),
(10, 'William Thomas', 'william@example.com', 'Germany'),
(11, 'Sophia Moore', 'sophia@example.com', 'USA'),
(12, 'Benjamin Jackson', 'benjamin@example.com', 'UK'),
(13, 'Chloe White', 'chloe@example.com', 'USA'),
(14, 'Jacob Harris', 'jacob@example.com', 'Canada'),
(15, 'Emma Martin', 'emma@example.com', 'Australia');


INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES
(101, 1, '2024-03-01', 100.00),
(102, 1, '2024-03-05', 150.00),
(103, 2, '2024-03-02', 200.00),
(104, 3, '2024-03-03', 75.00),
(105, 3, '2024-03-06', 125.00),
(106, 1, '2024-03-08', 180.00),
(107, 2, '2024-03-10', 220.00),
(108, 3, '2024-03-12', 100.00),
(109, 4, '2024-03-15', 75000.00),
(110, 5, '2024-03-16', 100000.00),
(111, 6, '2024-03-17', 60000.00),
(112, 7, '2024-03-18', 80000.00),
(113, 8, '2024-03-19', 90000.00),
(114, 9, '2024-03-20', 70000.00),
(115, 10, '2024-03-21', 120000.00),
(116, 11, '2024-03-22', 95000.00),
(117, 12, '2024-03-23', 55000.00),
(118, 13, '2024-03-24', 75000.00),
(119, 14, '2024-03-25', 85000.00),
(120, 15, '2024-03-26', 60000.00);


SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

SELECT C.CUSTOMER_NAME, SUM(O.TOTAL_AMOUNT) AS TOTAL_REVENUE FROM CUSTOMERS C 
JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_REVENUE DESC;