-- 2. Create a database structure for students and its college. One student can be in one college only. 

CREATE TABLE COLLEGE (
	COLLEGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    COLLEGE_NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    YEAR_OF_FOUND YEAR
);

CREATE TABLE STUDENTS (
	STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME VARCHAR(255) NOT NULL,
    AGE INT NOT NULL,
    CITY VARCHAR(150),
    GENDER ENUM('M', 'F', 'O'),
    COLLEGE_ID INT,
    FOREIGN KEY (COLLEGE_ID) REFERENCES COLLEGE(COLLEGE_ID)
);
