CREATE DATABASE CYBERCOM_CREATION;

USE CYBERCOM_CREATION;

-- SQL QUERIES 1:

-- 1. Create a database structure for products and categories. One product can be in more than one category and 
--    one category can have multiple products.

CREATE TABLE PRODUCTS (
	PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PRICE DECIMAL(10,2)
);

CREATE TABLE CATEGORIES (
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCTS_CATEGORIES (
	PRODUCT_ID INT,
    CATEGORY_ID INT,
    PRIMARY KEY (PRODUCT_ID, CATEGORY_ID) ,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);