-- 5. Write a SQL query to retrieve the names of all customers who have placed orders for products in the "Electronics" category, 
--    but have never placed an order for products in the "Clothing" category.

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERDETAILS;

SELECT C.CUSTOMERID, C.NAME FROM CUSTOMERS C
JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
WHERE P.CATEGORY = 'Electronics'
AND C.CUSTOMERID NOT IN (
	SELECT C2.CUSTOMERID FROM CUSTOMERS C2
	JOIN ORDERS O2 ON C2.CUSTOMERID = O2.CUSTOMERID
	JOIN ORDERDETAILS OD2 ON O.ORDERID = OD2.ORDERID
	JOIN PRODUCTS P2 ON OD2.PRODUCTID = P2.PRODUCTID
	WHERE P2.CATEGORY = 'Clothing'
)
GROUP BY CUSTOMERID;