-- 7. Write a SQL query to retrieve the names of all customers who have placed orders for more than five different products in the "Electronics" category.

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERDETAILS;

SELECT C.NAME FROM CUSTOMERS C 
JOIN ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
JOIN ORDERDETAILS OD ON O.ORDERID = OD.ORDERID
JOIN PRODUCTS P ON OD.PRODUCTID = P.PRODUCTID
WHERE P.CATEGORY = 'Electronics'
GROUP BY C.NAME
HAVING COUNT(DISTINCT P.PRODUCTID) > 5;