-- 5. Write a SQL query to retrieve the names of all customers who have made orders in the "orders" table, but have not made any orders in the last 90 days.

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;


SELECT C.CUSTOMER_NAME, GROUP_CONCAT(O.ORDER_DATE SEPARATOR ', ') AS 'ORDER DATE'
FROM CUSTOMERS C
INNER JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
WHERE C.CUSTOMER_ID NOT IN (
	SELECT C1.CUSTOMER_ID
	FROM CUSTOMERS C1
	INNER JOIN ORDERS O1
	ON C1.CUSTOMER_ID = O1.CUSTOMER_ID
	WHERE O1.ORDER_DATE >= DATE_SUB(CURRENT_DATE, INTERVAL 90 DAY)
	GROUP BY C1.CUSTOMER_ID)
GROUP BY C.CUSTOMER_ID;